name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  badges: ^3.0.2
  cloud_firestore: ^4.0.5
  cupertino_icons: ^1.0.5
  data_table_2: ^2.3.12
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_messaging: ^14.2.4
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  flutter_draggable_gridview: ^0.0.7
  flutter_reorderable_grid_view: ^4.0.0
  flutter_svg: ^1.1.6
  go_router: 5.1.1
  google_fonts: ^4.0.3
  intl: ^0.17.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  random_string:
  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

# https://stackoverflow.com/a/74234079/436422
#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
    - assets/images/
    - assets/icons/
